language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

env:
  global:
    # CLIENT_ID
    - secure:  WrFbvxbS/1aXCbvFZ5wlDe3Vy4oZIxEc8pfmVPGZKe4+bBOf3TOpuGywy8OA9S31+dzUQxp86JW97JOeTbS00X/L9z8Dpo1d1ZShh5SRNbmgrsJzgCGpjqVJo2hj7ZhA9JcIeDkq2N2wlh4+46RR9CTUZuUdwdhdhH1f9AU6m5eUJ8Qvw1nH9tPgncmiB47xzwJ61WQsawQFPWjGdLcOLK4mc71Ozh3zhpNXpwt0EU2J/Rxzl0CRsaSNpdDj+4m0Ar2cfMxBNC6t2sjKoaSQrjGqMo/5i1UPFBYNt91Yk9wFbeNyhY062TH6DkHyWMIi20ZeSQtwtQExsypESV1ZmJX0paP6XxsyoiyZMC8LoMa8JHsWtThA+L4VIpmONrJMFe/bnj27R9kyJg2FpzozUwYbw689ZcM5v/x2GpUzFMf4PvE41YG65a33+JD8YyKHTq9TnezaHeEGbqMe4k5gOjpxvU7TVqILFS3WnADtNt6UNolCiQ563dsZ/ds3YwEcesIpRzYVPWG73iI6f+vSk31NOwrw6Ac+tsYZjyRQYvV8vbh7BsB0ky0fr8wrTbzw2Htv7OBjOFrl4AmGPefX8w3yhsuGLbdKG8Kvy17eC9bFPQNs10vsQ3fVtytDJtAX663eVNquBPGGgkTwrCP1cFIjhd/jywU0O8cskle9iHU=
    # TENANT_ID
    - secure: 01yBkdLRCjFKtGFMAGxJ6M1M/MK2IXJ8ZC29CoQITQIvq7JocS/ZQhLu0/cqjwUHCMFeaIguiphnVo31vskhQndH7EB0NnuUX8UgyNZ7+ln7Un0KeGuhe1xhfI9hAkl8v2YMEcp127mO4YVl7OAwHjAYHR0EGi+kkPiOiOEElFD4whruTXAnueMlW49NhPUaKENEn/Ll2xNsHBJNycRb6Uk+NKcMTa68nrT/GNyKiXEWhoWC9KlaTJQYeN2mQ6dFlW2OY0PsOWNbGCXeUBda9xM3DLW116j9hnmk6PY20UrNJUdUrXPaz6Y5AgXcs81D+xO1FxUFUusIqC7zILTC6egHb5r1p5EuNp4l1JBP9+K223MRs4/LnCOAXolIavDZKwmp2iWSoQM8+sQ6z7UglkoybT8z+GqC5r0ZqHraVxXBbR1Nx0vLH62CtGhpkDasky31sSXdHil+tOCkD/zgsFEHrpL0+sVwY1tZEWOlyGDjDm/XMAlPGfm9tsifTQSoKMc4jENFq/PbJMqRZI2OeObHCU1UF7/eCU7S7jL7Spyn/be+g/cvW7s8ZprJa9o5xLnFv+LwMD2klJCTooXSyvgfN6HhrS37rm/YDDqgNqDWAZq30majpAKXD1niMSNhlA6fKVtS/uGkqcN1RQYc6uz+XQ6Dz7/2HA0bMxaHx8Q=
    # KEY
    - secure: yLZyoxdqFU26hgHuA+fCqyy5FUMUOj/K0jfSZ7SjLSVcItESwTtk2GKF2JmWAp6415VfqCYhfKAw+/vEKg6OaEX+J7HuSiir/Ji0bF6rLexaMiJEoMW2sdHiT8cPjZnjJCOe+p/otB4wzcjGBE8yuJ/QqKQVXF0qgclJbtgo1AR1C8ojBoCXondVPilVvo5CJFhBbNlQGY5ZI2cLlgLthl7XSdChTMscv2dRLP0nHhXLDPKakBbAJmFnsQt6x7BhzolKQcHcMUluap9xygJNN9nuTfRMqlHWXuvkkXUrKpV8HmV1QYaUdWL0y8jiRvyuowhtXGfO4y8Vlrx7glF15LMecPAnoGkFnRv1tnEYODX8VAlYkVeu6wQ1HYDWQPyO8xz+SaCSKobSRrqrZd18d5A2xHi1nxibpG+rZ+2jRUamOSEUG/vcsBYS8Um0UyEPcFDyXQX1tVvVWIT8XiQOOXHO/YPHFywaInXpPVF4JWFj35KFPynvYxmGt0W9RJyyVYTiqkFMOCRokq/6g5BRJIX7szSgEWRGplXs93FYdWsOA2DwQnhtYTUyYtJtz4lPR/fPz6MJS6xJEnWGAZ3woLAdWact60wfxYseK+yknuPHY3IWMrBLXPhwu14e6FlQpVWW4HJOXYf+PLVSoNhTF1InI9gKq9GXXsm+FzIWbVM=

before_install:
  - sudo apt-get update && sudo apt-get install -y libssl-dev libffi-dev python-dev build-essential
  - sudo pip install azure-cli

script:
  - "./mvnw verify -P it"
  - "./mvnw cobertura:cobertura"

after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)
